#!/bin/bash

if [ -n $SLURM_JOBID ]
then
  if [ "$(ls -A $TMPDIR)" ]
  then
    CERT_SIZE="Certificate size: "
    CERT_SIZE+=$(du -bck -- $TMPDIR/* | tail -n 1)
    echo $CERT_SIZE | sed -e "s/ total$//"
  else
    echo "Certificate size: 0"
  fi
  echo "File size of hints.txt: `stat -c %s $TMPDIR/hints.txt 2> nul`"
  echo "File size of states.bdd: `stat -c %s $TMPDIR/states.bdd 2> nul`"
  echo "File size of h_cert.bdd: `stat -c %s $TMPDIR/h_cert.bdd 2> nul`"

fi
